<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * ═══════════════════════════════════════════════════════════════════
 * MedicinesSeeder — كتالوج الأدوية الكامل
 * ═══════════════════════════════════════════════════════════════════
 *
 * المصدر: Medicines.xlsx
 *
 * المبدأ:
 *   ✅ يعتمد على الوحدات المُنشأة مسبقاً في CoreDataSeeder
 *   ✅ لا يُنشئ وحدات جديدة في جدول units (إلا إن كانت ناقصة)
 *   ✅ يستخدم معامل افتراضي = 1 لكل الوحدات
 *   ✅ idempotent (يمكن تشغيله أكثر من مرة بأمان)
 *
 * التشغيل:
 *   php artisan db:seed --class=MedicinesSeeder
 *
 * أو تلقائياً بعد CoreDataSeeder عبر DatabaseSeeder.
 * ═══════════════════════════════════════════════════════════════════
 */
class MedicinesSeeder extends Seeder
{
    /**
     * خريطة تحويل رموز Excel إلى رموز جدول units
     *
     * الوحدات المركبة (box-strip) تُفكَّك إلى وحدتين منفصلتين.
     */
    private const UNIT_MAP = [
        // رموز مباشرة
        'box'    => 'BOX',
        'strip'  => 'STRIP',
        'pic'    => 'PIC',
        'piece'  => 'PIECE',
        'pc'     => 'PIC',
        'tab'    => 'TAB',
        'cap'    => 'CAP',
        'bottle' => 'BOTTLE',
        'bot'    => 'BOTTLE',
        'tube'   => 'TUBE',
        'tub'    => 'TUB',
        'vial'   => 'VIAL',
        'amp'    => 'AMP',
        'ampul'  => 'AMP',
        'spray'  => 'SPRAY',
        'sachet' => 'SACHET',
        'ml'     => 'ML',
        'g'      => 'G',
        'drop'   => 'DROP',
        'inh'    => 'INH',
        'drip'   => 'DRIP',
        'set'    => 'SET',
        'supp'   => 'SUPP',
    ];

    public function run(): void
    {
        $this->command->info('🚀 بدء MedicinesSeeder...');

        // التأكد من وجود الوحدات الأساسية
        $units = $this->loadUnits();
        if (empty($units)) {
            $this->command->error('❌ لا توجد وحدات في جدول units. شغّل CoreDataSeeder أولاً.');
            return;
        }

        $created = 0;
        $updated = 0;
        $unitsCreated = 0;

        DB::transaction(function () use ($units, &$created, &$updated, &$unitsCreated) {
            foreach ($this->getMedicines() as $medicine) {
                $name = trim($medicine['name'] ?? '');
                if ($name === '') continue;

                // ابحث عن الدواء أو أنشئه
                $medicineId = DB::table('medicines')->where('name', $name)->value('id');

                if (!$medicineId) {
                    $medicineId = DB::table('medicines')->insertGetId([
                        'name'             => $name,
                        'scientific_name'  => null,
                        'notes'            => null,
                        'pricing_method'   => 'local',
                        'pricing_rule_id'  => null,
                        'category_id'      => null,
                        'strips_per_box'   => 1,
                        'pieces_per_strip' => 1,
                        'allow_box_sale'   => 1,
                        'allow_strip_sale' => 1,
                        'allow_piece_sale' => 1,
                        'created_at'       => now(),
                        'updated_at'       => now(),
                    ]);
                    $created++;
                } else {
                    DB::table('medicines')
                        ->where('id', $medicineId)
                        ->update(['updated_at' => now()]);
                    $updated++;
                }

                // اربط الوحدات بالدواء
                $unitsCreated += $this->attachUnits(
                    $medicineId,
                    $medicine['unit'] ?? null,
                    $units
                );
            }
        });

        $this->command->line("   ✅ {$created} دواء جديد، {$updated} محدّث");
        $this->command->line("   ✅ {$unitsCreated} ربط وحدة/دواء");
        $this->command->info('✅ اكتمل MedicinesSeeder.');
    }

    /**
     * تحميل الوحدات من قاعدة البيانات
     */
    private function loadUnits(): array
    {
        return DB::table('units')
            ->where('active', 1)
            ->pluck('id', 'symbol')
            ->toArray();
    }

    /**
     * ربط الوحدات بدواء معين
     *
     * @return int عدد الروابط المُنشأة
     */
    private function attachUnits(int $medicineId, ?string $definition, array $units): int
    {
        if (!$definition) return 0;

        $definition = strtolower(trim($definition));
        if ($definition === '') return 0;

        $parts = explode('-', $definition);
        $created = 0;
        $sortOrder = 1;

        foreach ($parts as $index => $part) {
            $part = trim($part);
            if ($part === '') continue;

            $symbol = self::UNIT_MAP[$part] ?? null;
            if (!$symbol || !isset($units[$symbol])) continue;

            $unitId = $units[$symbol];
            $isBase = ($index === count($parts) - 1) ? 1 : 0;

            // تجنّب التكرار
            $exists = DB::table('medicine_units')
                ->where('medicine_id', $medicineId)
                ->where('unit_id', $unitId)
                ->exists();

            if ($exists) {
                $sortOrder++;
                continue;
            }

            DB::table('medicine_units')->insert([
                'medicine_id' => $medicineId,
                'unit_id'     => $unitId,
                'factor'      => 1,
                'barcode'     => null,
                'is_base'     => $isBase,
                'sort_order'  => $sortOrder,
                'allow_sale'  => 1,
                'created_at'  => now(),
                'updated_at'  => now(),
            ]);

            $created++;
            $sortOrder++;
        }

        return $created;
    }

    /**
     * قائمة الأدوية الكاملة من ملف Medicines.xlsx
     */
    private function getMedicines(): array
    {
        return [
            // ═══════════ الجزء 1 ═══════════
            ['name' => 'Conther 80/480', 'unit' => 'box-strip'],
            ['name' => 'Lumiart 80/480', 'unit' => 'box-strip'],
            ['name' => 'Artemether 20/120', 'unit' => 'box'],
            ['name' => 'Amidpine 5mg', 'unit' => 'box-strip'],
            ['name' => 'HCQ 200', 'unit' => 'box-strip'],
            ['name' => 'Prima Pro', 'unit' => 'box-strip'],
            ['name' => 'Hero Lac 1', 'unit' => 'box-strip'],
            ['name' => 'Pretty Lac LF', 'unit' => 'box'],
            ['name' => 'Stevia', 'unit' => 'box-strip'],
            ['name' => 'Doxim 200', 'unit' => 'box'],
            ['name' => 'Bactofix 400', 'unit' => 'box-strip'],
            ['name' => 'Amixime 400', 'unit' => 'box-strip'],
            ['name' => 'Amixime 200', 'unit' => 'box'],
            ['name' => 'Nilozol 250', 'unit' => 'box-strip'],
            ['name' => 'Syrine 3ml', 'unit' => 'pic'],
            ['name' => 'Edizone 500', 'unit' => 'vial'],
            ['name' => 'Ceftriol 1000mg', 'unit' => 'vial'],
            ['name' => 'Vision-Aid', 'unit' => 'box'],
            ['name' => 'Vitan 3', 'unit' => 'box-strip'],
            ['name' => 'Mecovil 12', 'unit' => 'box'],
            ['name' => 'Nervon 500', 'unit' => 'box'],
            ['name' => 'Mecoba 500', 'unit' => 'box-strip'],
            ['name' => 'Vitamin B12 1000', 'unit' => 'box'],
            ['name' => 'Neurovox', 'unit' => 'box-strip'],
            ['name' => 'Omevox', 'unit' => 'box-strip'],
            ['name' => 'Carnitine Forte', 'unit' => 'box-strip'],
            ['name' => 'Nutramax', 'unit' => 'box-strip'],
            ['name' => 'Nutramax Gold', 'unit' => 'box-strip'],
            ['name' => 'Diavox', 'unit' => 'box-strip'],
            ['name' => 'Fertilex Men', 'unit' => 'box-strip'],
            ['name' => 'Lumiart 20/120', 'unit' => 'box-strip'],
            ['name' => 'Daflon 500', 'unit' => 'box-strip'],
            ['name' => 'Cod Liver Oil', 'unit' => 'box-strip'],
            ['name' => 'HG 9 Sachet', 'unit' => 'box-strip'],
            ['name' => 'Fertilex Women', 'unit' => 'box-strip'],
            ['name' => 'Amiron +F', 'unit' => 'box-strip'],
            ['name' => 'Ferolin', 'unit' => 'box-strip'],
            ['name' => 'Haemovox', 'unit' => 'box-strip'],
            ['name' => 'Ferron Forte', 'unit' => 'box-strip'],
            ['name' => 'Fe-Full', 'unit' => 'box-strip'],
            ['name' => 'Vitaferol', 'unit' => 'box-strip'],
            ['name' => 'Bonvox 500', 'unit' => 'box-strip'],
            ['name' => 'Cali Pure', 'unit' => 'box-strip'],
            ['name' => 'Calim', 'unit' => 'box-strip'],
            ['name' => 'Enzyrex', 'unit' => 'box-strip'],
            ['name' => 'SB-First', 'unit' => 'box-strip'],
            ['name' => 'Bisadyl', 'unit' => 'box-strip'],
            ['name' => 'Pregnavox', 'unit' => 'box-strip'],
            ['name' => 'Joemega 3', 'unit' => 'box-strip'],
            ['name' => 'Omega Best', 'unit' => 'box-strip'],
            ['name' => 'Liver Heal', 'unit' => 'box-strip'],
            ['name' => 'HSN', 'unit' => 'box-strip-tab'],
            ['name' => 'Fenugreek', 'unit' => 'box-strip'],
            ['name' => 'Norethisterone', 'unit' => 'box-strip'],
            ['name' => 'Norcutin', 'unit' => null],
            ['name' => 'Norazor', 'unit' => 'box-strip'],
            ['name' => 'CD Solicin 10', 'unit' => 'box-strip'],
            ['name' => 'Virustat 200', 'unit' => 'box-strip'],
            ['name' => 'Virustat 400', 'unit' => 'box-strip'],
            ['name' => 'Injidime 1g', 'unit' => 'vial'],
            ['name' => 'Trizid 1000', 'unit' => 'vial'],
            ['name' => 'Injroxime 750', 'unit' => 'vial'],
            ['name' => 'Xiotil 750', 'unit' => 'vial'],
            ['name' => 'Funtum 1.5g', 'unit' => 'vial'],
            ['name' => 'Meroscot 1g', 'unit' => 'vial'],
            ['name' => 'Monan 1g', 'unit' => 'vial'],
            ['name' => 'Edispoin 100', 'unit' => 'box-strip'],
            ['name' => 'Aspruna 100', 'unit' => 'box-strip'],
            ['name' => 'Faderin 100', 'unit' => 'box-strip'],
            ['name' => 'Aspruna 75', 'unit' => 'box-strip'],
            ['name' => 'Edisprin 75', 'unit' => 'box-strip'],
            ['name' => 'Aspicor 75', 'unit' => 'box-strip'],
            ['name' => 'Forsitor 20', 'unit' => 'box-strip'],
            ['name' => 'Cholerose 10mg', 'unit' => 'box-strip'],
            ['name' => 'Amistatin 40', 'unit' => 'box-strip'],
            ['name' => 'Atornova 20', 'unit' => 'box-strip'],
            ['name' => 'Biscot', 'unit' => 'box-strip'],
            ['name' => 'Amicor 5mg', 'unit' => 'box-strip'],
            ['name' => 'Amicor 2.5mg', 'unit' => 'box-strip'],
            ['name' => 'Amidipin 10mg', 'unit' => 'box-strip'],
            ['name' => 'CD Amlovan 10/160', 'unit' => 'box-strip'],
            ['name' => 'CD Amlovan 5/160', 'unit' => 'box-strip'],
            ['name' => 'CD Amlovan 5/180', 'unit' => 'box-strip'],
            ['name' => 'Angiosar Plus 160/5', 'unit' => 'box-strip'],
            ['name' => 'Angiosar Plus 160/10', 'unit' => 'box-strip'],
            ['name' => 'Lisinopril 20mg', 'unit' => 'box-strip'],
            ['name' => 'Lisinopril 10mg', 'unit' => 'box-strip'],
            ['name' => 'CD Pril 10mg', 'unit' => 'box-strip'],
            ['name' => 'Zinopril 5mg', 'unit' => 'box-strip'],
            ['name' => 'Sinopril', 'unit' => 'box-strip'],
            ['name' => 'Azapril 2.5', 'unit' => 'box-strip'],
            ['name' => 'Corzide 25', 'unit' => 'box-strip'],
            ['name' => 'Torsemide 20', 'unit' => 'box-strip'],
            ['name' => 'Diurex 25', 'unit' => 'box-strip'],
            ['name' => 'Spirdacton 25', 'unit' => 'box-strip'],
            ['name' => 'Spirolon 25', 'unit' => 'box-strip'],
            ['name' => 'Candestan 8mg', 'unit' => 'box-strip'],
            ['name' => 'Candiscot 16', 'unit' => 'box-strip'],
            ['name' => 'Candiscot Plus', 'unit' => 'box-strip'],
            ['name' => 'Candalkan Plus', 'unit' => 'box-strip'],
            ['name' => 'Candestan Plus', 'unit' => 'box-strip'],
            ['name' => 'Coryl 0.25mg', 'unit' => 'box-strip'],
            ['name' => 'Amilosan 50', 'unit' => 'box-strip'],
            ['name' => 'Amilosan C 50/12.5', 'unit' => 'box-strip'],
            ['name' => 'Nifelat 20mg', 'unit' => 'box-strip'],
            ['name' => 'Cozal 25', 'unit' => 'box-strip'],
            ['name' => 'Isorem 10', 'unit' => 'box-strip'],
            ['name' => 'CD Maryl 4', 'unit' => 'box-strip'],
            ['name' => 'Amipride 4', 'unit' => 'box-strip'],
            ['name' => 'Pirmyl 4', 'unit' => 'box-strip'],
            ['name' => 'Getryl 3', 'unit' => 'box-strip'],
            ['name' => 'Glemizal 3', 'unit' => 'box-strip'],
            ['name' => 'Amipride 2', 'unit' => 'box-strip'],
            ['name' => 'Pirmyl I', 'unit' => 'box-strip'],
            ['name' => 'CD Vilda 50', 'unit' => 'box-strip'],
            ['name' => 'Uniphage 500', 'unit' => 'box-strip'],
            ['name' => 'Amifortmin 850', 'unit' => 'box-strip'],
            ['name' => 'Daophage 850', 'unit' => 'box-strip'],
            ['name' => 'CD Formin 1000', 'unit' => 'box-strip'],
            ['name' => 'Prewell', 'unit' => 'box-strip'],
            ['name' => 'Zinc Tab', 'unit' => 'box-strip'],
            ['name' => 'Vilget M 50/850', 'unit' => 'box-strip'],
            ['name' => 'CD Betavert 8', 'unit' => 'box-strip'],
            ['name' => 'Super D3', 'unit' => 'box-strip'],
            ['name' => 'Nephrio', 'unit' => 'box-strip'],
            ['name' => 'Folic Acid', 'unit' => 'box-strip'],
            ['name' => 'Clofinil 75mg', 'unit' => 'box-strip'],
            ['name' => 'Amifenac 100sr', 'unit' => 'box-strip'],
            ['name' => 'Qunine Sulphate', 'unit' => 'box-strip'],
            ['name' => 'Difisal SR 100', 'unit' => 'box-strip'],
            ['name' => 'Balnac 50', 'unit' => 'box-strip'],
            ['name' => 'Paplofen P 50', 'unit' => 'box-strip'],
            ['name' => 'Divido 75mg', 'unit' => 'box-strip'],
            ['name' => 'Gm Menapon 500', 'unit' => 'box-strip'],
            ['name' => 'Miocran Uro', 'unit' => 'box-strip'],
            ['name' => 'Exit 400', 'unit' => 'box-strip-tab'],
            ['name' => 'Vermorex 100', 'unit' => 'box-strip'],
            ['name' => 'CD Mendazole 100', 'unit' => 'bottle'],
            ['name' => 'Mebendazole Susp', 'unit' => 'bottle'],
            ['name' => 'Verem One 500', 'unit' => 'tab'],
            ['name' => 'CD Bralix 5/2.5', 'unit' => 'box-strip'],
            ['name' => 'Tenaxit', 'unit' => null],
            ['name' => 'Colospasmin 100mg', 'unit' => 'box-strip'],
            ['name' => 'Colospasmin 135', 'unit' => 'box-strip'],
            ['name' => 'Amilans 30', 'unit' => 'box-strip'],
            ['name' => 'CD esmol 40mg', 'unit' => 'box-strip'],
            ['name' => 'CD esmol 20mg', 'unit' => 'box-strip'],
            ['name' => 'Esomeprazole 40', 'unit' => 'box-strip'],
            ['name' => 'Pantin 40mg', 'unit' => 'box-strip'],
            ['name' => 'Pantoprazole 40', 'unit' => 'box-strip'],
            ['name' => 'Pantodac 20', 'unit' => 'box-strip'],
            ['name' => 'Omefiz 20', 'unit' => 'box-strip'],
            ['name' => 'Omescot 20', 'unit' => 'box-strip'],
            ['name' => 'CD Flat 125/500', 'unit' => 'box-strip'],
            ['name' => 'Flatidyl', 'unit' => 'box-strip'],
            ['name' => 'Imodal 2mg', 'unit' => 'box-strip'],
            ['name' => 'Domivent 10', 'unit' => 'box-strip'],
            ['name' => 'Perprasol Inj 40', 'unit' => 'vial'],
            ['name' => 'Ondal 8', 'unit' => 'box-strip'],
            ['name' => 'Navoproxin Plus', 'unit' => 'box-strip'],
            ['name' => 'Vitamin B6', 'unit' => 'box-strip'],
            ['name' => 'Senagyl 500', 'unit' => 'box-strip'],
            ['name' => 'Domigest', 'unit' => 'box-strip'],
            ['name' => 'Lact Oral Salu', 'unit' => 'bottle'],
            ['name' => 'Laxopeg Syrup', 'unit' => 'bottle'],
            ['name' => 'Fasigast 500', 'unit' => 'box-strip'],
            ['name' => 'Tinigyl 500', 'unit' => 'box-strip'],
            ['name' => 'Protozole', 'unit' => 'box-strip'],
            ['name' => 'Getal 1000', 'unit' => 'box-strip'],
            ['name' => 'Barkaphon', 'unit' => 'box-strip'],
            ['name' => 'Mylobac', 'unit' => 'box-strip'],
            ['name' => 'Epigesic', 'unit' => 'box-strip'],
            ['name' => 'Meloxidol 15mg', 'unit' => 'box-strip'],
            ['name' => 'Mobizal 15mg', 'unit' => 'box-strip'],
            ['name' => 'Mobizal 7.5mg', 'unit' => 'box-strip'],
            ['name' => 'Ibuscot 200mg', 'unit' => 'box-strip'],
            ['name' => 'Ibu 400mg', 'unit' => 'box-strip'],
            ['name' => 'CD Histin 5', 'unit' => 'box-strip'],
            ['name' => 'CD Levotrizin', 'unit' => 'box-strip'],
            ['name' => 'Ebastel 20', 'unit' => 'box-strip'],
            ['name' => 'Loratadine 10', 'unit' => 'box-strip'],
            ['name' => 'Ebastel 10', 'unit' => 'box-strip'],
            ['name' => 'Furosix', 'unit' => 'amp'],
            ['name' => 'Benzyle Penicillin', 'unit' => 'vial'],
            ['name' => 'Benzathine Bencillin 1.2', 'unit' => 'vial'],
            ['name' => 'CD Duolast 100/60', 'unit' => 'box-strip-tab'],
            ['name' => 'Azafil 100', 'unit' => 'box'],
            ['name' => 'Virecta 100', 'unit' => 'box-strip-tab'],
            ['name' => 'CDafil 20', 'unit' => 'box-strip'],
            ['name' => 'Imutrexate 2.5', 'unit' => 'box-strip'],
            ['name' => 'Myteka 10mg', 'unit' => 'box-strip'],
            ['name' => 'CD ogrel 75mg', 'unit' => 'box-strip'],
            ['name' => 'Decalerto 20', 'unit' => 'box-strip'],
            ['name' => 'Rivaflowva 20', 'unit' => 'box-strip'],
            ['name' => 'Varoxa', 'unit' => 'box-strip'],
            ['name' => 'Nazomed 400', 'unit' => 'box-strip'],
            ['name' => 'Gynoq Mikozal', 'unit' => 'box-strip'],
            ['name' => 'Monicure 200', 'unit' => 'box-strip'],
            ['name' => 'Profulcan 150', 'unit' => 'box-tab'],
            ['name' => 'CD Itrazol 100', 'unit' => 'box-strip'],
            ['name' => 'Grisoral 125', 'unit' => 'box-strip'],
            ['name' => 'Metonorm', 'unit' => 'amp'],
            ['name' => 'CD H Gvine', 'unit' => 'box-strip'],
            ['name' => 'Airrtal 100', 'unit' => 'box-strip'],
            ['name' => 'Aceclo 100', 'unit' => 'box-strip'],
            ['name' => 'Erythromycin', 'unit' => 'box-strip'],
            ['name' => 'CD Claricin 500', 'unit' => 'box-strip'],
            ['name' => 'Nafrafloxacin 500', 'unit' => 'box-strip'],
            ['name' => 'Unitariqin 400', 'unit' => 'box-strip'],
            ['name' => 'Wafranor 400', 'unit' => 'box-strip'],
            ['name' => 'Levoscot 500', 'unit' => 'box-strip'],
            ['name' => 'CD Linozid', 'unit' => 'box-strip'],
            ['name' => 'Xiotil 500', 'unit' => 'box-strip'],
            ['name' => 'Zetum 500', 'unit' => 'box-strip'],
            ['name' => 'GM Zirocin 500', 'unit' => 'box-strip'],
            ['name' => 'Zithroset 500', 'unit' => 'box-strip'],
            ['name' => 'Amoclan 375mg', 'unit' => 'box-strip'],
            ['name' => 'Clavimax 625', 'unit' => 'box-strip'],
            ['name' => 'Novamentin 625', 'unit' => 'box-strip'],
            ['name' => 'Amiclav 1000mg', 'unit' => 'box-strip'],
            ['name' => 'Novamentin 1000mg', 'unit' => 'box-strip'],
            ['name' => 'Clovimax 457', 'unit' => 'bottle'],
            ['name' => 'Sky Gloves', 'unit' => 'box-strip'],
            ['name' => 'Depox 200', 'unit' => 'box-strip'],
            ['name' => 'Olabenz 5mg', 'unit' => 'box-strip'],
            ['name' => 'Famila', 'unit' => 'box-strip'],
            ['name' => 'Microgenest', 'unit' => 'box-strip'],
            ['name' => 'Sogestedin', 'unit' => 'box-strip'],
            ['name' => 'T4 Thyro 100', 'unit' => 'box-strip'],
            ['name' => 'Neo Mecrazole', 'unit' => 'box-strip'],
            ['name' => 'Carbimazole 5', 'unit' => 'box-strip'],
            ['name' => 'Novofen 10mg', 'unit' => 'box-strip'],
            ['name' => 'Dosin 4mg', 'unit' => 'box-strip'],
            ['name' => 'Xalgetz 0.4', 'unit' => 'box-strip'],
            ['name' => 'Prostacin 0.4', 'unit' => 'box-strip'],
            ['name' => 'Prostride 5mg', 'unit' => 'box-strip'],
            ['name' => 'Carduduex 4', 'unit' => 'box-strip'],
            ['name' => 'Tobrin 03%', 'unit' => 'drop'],
            ['name' => 'Iventi D', 'unit' => 'drop'],
            ['name' => 'Epifenac 1mg', 'unit' => 'drop'],
            ['name' => 'Alphabrinzima', 'unit' => 'drop'],
            ['name' => 'Zonacip', 'unit' => 'drop'],
            ['name' => 'Neo Pol E.d', 'unit' => 'drop'],
            ['name' => 'Normo Tears', 'unit' => 'drop'],
            ['name' => 'Brimodin 0.2%', 'unit' => 'drop'],
            ['name' => 'Brimosalm 0.15', 'unit' => 'drop'],
            ['name' => 'Prisoline', 'unit' => 'drop'],
            ['name' => 'Dextrobac', 'unit' => 'drop'],
            ['name' => 'Oxcin', 'unit' => 'drop'],
            ['name' => 'Nostamine', 'unit' => 'drop'],
            ['name' => 'Atazol 0.05%', 'unit' => 'drop'],
            ['name' => 'Antazol', 'unit' => 'drop'],
            ['name' => 'Ojoblick', 'unit' => 'drop'],
            ['name' => 'Cortis 250', 'unit' => 'inh'],
            ['name' => 'No Uric 300mg', 'unit' => 'box-strip'],
            ['name' => 'No Uric 100mg', 'unit' => 'box-strip'],
            ['name' => 'CD Anxitin 20', 'unit' => 'box-strip'],
            ['name' => 'Amirol 10mg', 'unit' => 'box-strip'],
            ['name' => 'Haloxen 5mg', 'unit' => 'box-strip'],
            ['name' => 'Travast 0.004', 'unit' => 'drop'],
            ['name' => 'Travast Plus', 'unit' => 'drop'],
            ['name' => 'Ramedazolmide', 'unit' => 'drop'],
            ['name' => 'Acetazolamide 250', 'unit' => 'box-strip'],
            ['name' => 'Amitriptyline', 'unit' => 'box-strip'],
            ['name' => 'Topilept 100', 'unit' => 'box-strip'],
            ['name' => 'CD Parkidopa 250', 'unit' => 'box-strip'],
            ['name' => 'CD Rispdon 2mg', 'unit' => 'box-strip'],
            ['name' => 'CD Rispdon 4mg', 'unit' => 'box-strip'],
            ['name' => 'Tabunex 0.05%', 'unit' => 'box-strip'],
            ['name' => 'Dexatrol', 'unit' => 'tab'],
            ['name' => 'Nasosal Plus', 'unit' => 'inh'],
            ['name' => 'Nasosal Hyper', 'unit' => 'inh'],
            ['name' => 'Ipratom 250/2', 'unit' => 'box-strip'],
            ['name' => 'CD Cetam 500', 'unit' => 'box-strip'],
            ['name' => 'Levnoseiz 500', 'unit' => 'box-strip'],
            ['name' => 'Levetiracetam 500', 'unit' => 'box-strip'],
            ['name' => 'Levnoseiz 1000', 'unit' => 'box-strip'],
            ['name' => 'Lanzapine 10mg', 'unit' => 'box-strip'],
            ['name' => 'Excelsa 20mg', 'unit' => 'box-strip'],
            ['name' => 'Citanew 10mg', 'unit' => 'box-strip'],
            ['name' => 'Tolopram 40mg', 'unit' => 'box-strip'],
            ['name' => 'Depretin 40mg', 'unit' => 'box-strip'],
            ['name' => 'Valpromeal Syrup', 'unit' => 'bottle'],
            ['name' => 'Depavalpolem Syrup', 'unit' => 'bottle'],
            ['name' => 'Depox 500', 'unit' => 'box-strip'],
            ['name' => 'CD Gapentin 100', 'unit' => 'box-strip'],
            ['name' => 'Gabix 300mg', 'unit' => 'box-strip'],
            ['name' => 'Gabica 75mg', 'unit' => 'box-strip'],
            ['name' => 'Carbatec 400sr', 'unit' => 'box-strip'],
            ['name' => 'Hayalepsin 200', 'unit' => 'box-strip'],
            ['name' => 'Clavimax 1g', 'unit' => 'box-strip'],
            ['name' => 'Amiclav 625', 'unit' => 'box-strip'],
            ['name' => 'Predilone 5mg', 'unit' => 'box-strip'],
            ['name' => 'Predinsol CD 5', 'unit' => 'box-strip'],
            ['name' => 'Dr Altag', 'unit' => 'drop'],
            ['name' => 'N.S Nasal Drop', 'unit' => 'drop'],
            ['name' => 'Clove Oil', 'unit' => 'drop'],
            ['name' => 'Flancogyl 500', 'unit' => 'box-strip'],
            ['name' => 'Amindazol 500', 'unit' => 'box-strip'],
            ['name' => 'Multi Vit', 'unit' => 'box-strip'],
            ['name' => 'Proditil 100ps', 'unit' => 'box-strip'],
            ['name' => 'Azimax 250', 'unit' => 'box-strip'],
            ['name' => 'Electroscot', 'unit' => 'pic'],
            ['name' => 'S Nubeno 5ml', 'unit' => 'drop'],
            ['name' => 'Avalon Cream', 'unit' => 'box'],
            ['name' => 'Spotless Face Cream', 'unit' => 'tub'],
            ['name' => 'CD Anagrow', 'unit' => 'box'],
            ['name' => 'Baby Talcun Powder', 'unit' => 'pic'],
            ['name' => 'Zinc Nova', 'unit' => 'pic'],
            ['name' => 'Newday Mouth Wash', 'unit' => 'bottle'],
            ['name' => 'Orex Spray', 'unit' => 'spray'],
            ['name' => 'Smarth Xiden', 'unit' => 'pic'],
            ['name' => 'Clear Plus Soap', 'unit' => 'pic'],
            ['name' => 'Saliderm Soap', 'unit' => 'pic'],
            ['name' => 'Scalix Soap', 'unit' => 'pic'],
            ['name' => 'Scabiderm Soap', 'unit' => 'pic'],
            ['name' => 'Actolind', 'unit' => 'pic'],
            ['name' => 'Diabetic Foot', 'unit' => 'pic'],
            ['name' => 'CD Sitaburn', 'unit' => 'pic'],
            ['name' => 'Honey Care', 'unit' => 'pic'],
            ['name' => 'Sulphagin Cream', 'unit' => 'pic'],
            ['name' => 'Crampnil D', 'unit' => 'pic'],
            ['name' => 'Sito Heal', 'unit' => 'pic'],
            ['name' => 'Magic Cream', 'unit' => 'pic'],
            ['name' => 'Dektazok', 'unit' => 'tab'],
            ['name' => 'Melanthenol', 'unit' => 'tub'],
            ['name' => 'Panthenova B5', 'unit' => 'tub'],
            ['name' => 'Glow Fresh', 'unit' => 'bottle'],
            ['name' => 'Alfacort', 'unit' => 'pic'],
            ['name' => 'Pilax', 'unit' => 'pic'],
            ['name' => 'Proto Heal', 'unit' => 'pic'],
            ['name' => 'Betaderm', 'unit' => 'pic'],
            ['name' => 'Betamet', 'unit' => 'pic'],
            ['name' => 'CD Metazone', 'unit' => 'pic'],
            ['name' => 'Fueidel', 'unit' => 'pic'],
            ['name' => 'Fucine', 'unit' => 'pic'],
            ['name' => 'Fusiderm', 'unit' => 'pic'],
            ['name' => 'CD Tetracin', 'unit' => 'pic'],
            ['name' => 'Supracyline', 'unit' => 'pic'],
            ['name' => 'Teranova', 'unit' => 'pic'],
            ['name' => 'Panaderm', 'unit' => 'pic'],
            ['name' => 'Ketacor', 'unit' => 'tub'],
            ['name' => 'Sicacyline', 'unit' => 'tub'],
            ['name' => 'Exinofin', 'unit' => 'tab'],
            ['name' => 'CD Acnestop', 'unit' => 'tub'],
            ['name' => 'Clovirex Cream', 'unit' => 'tub'],
            ['name' => 'Tetracycline', 'unit' => 'tab'],
            ['name' => 'Candid B', 'unit' => 'tube'],
            ['name' => 'Candid', 'unit' => 'tube'],
            ['name' => 'Cortiderm 1%', 'unit' => 'pic'],
            ['name' => 'Betafucin', 'unit' => 'tab'],
            ['name' => 'Sica Numb', 'unit' => 'tub'],
            ['name' => 'Rutgard Mouth Gel', 'unit' => 'pic'],
            ['name' => 'Retinoid', 'unit' => 'tub'],
            ['name' => 'Supirocin', 'unit' => null],
            ['name' => 'Solache', 'unit' => 'tub'],
            ['name' => 'Melano Massage', 'unit' => 'tub'],
            ['name' => 'Crampsal', 'unit' => 'tub'],
            ['name' => 'Voligesic Plus', 'unit' => 'tub'],
            ['name' => 'Feminova', 'unit' => 'bottle'],
            ['name' => 'Castor Oil', 'unit' => 'bottle'],
            ['name' => 'Peridone Syrup', 'unit' => 'bottle'],
            ['name' => 'Domivent', 'unit' => 'bottle'],
            ['name' => 'Kojic Glow', 'unit' => 'pic'],
            ['name' => 'D Lamis', 'unit' => 'pic'],
            ['name' => 'Ichthamol 10%', 'unit' => 'pic'],
            ['name' => 'Ferpod 100mg', 'unit' => 'box-strip'],
            ['name' => 'Glutavit Soap', 'unit' => 'pic'],
            ['name' => 'Deflat Droporal', 'unit' => 'bottle'],
            ['name' => 'Arnil Gel', 'unit' => 'tub'],
            ['name' => 'Powergel', 'unit' => 'tub'],
            ['name' => 'D max V.D3', 'unit' => 'bottle'],
            ['name' => 'Chipodox 100', 'unit' => 'bottle'],
            ['name' => 'Stopain', 'unit' => 'tub'],
            ['name' => 'Royal Vaseline', 'unit' => 'pic'],
            ['name' => 'Follaxcel Vaseline', 'unit' => 'pic'],
            ['name' => 'Herbal Cough', 'unit' => 'box-strip'],
            ['name' => 'CD Cefcloxime', 'unit' => 'bottle'],
            ['name' => 'Green Zyme', 'unit' => 'bottle'],
            ['name' => 'Orazone Syrup', 'unit' => 'bottle'],
            ['name' => 'Power Cort', 'unit' => 'tube'],
            ['name' => 'Maeva', 'unit' => 'pic'],
            ['name' => 'Adult Pants', 'unit' => 'pic'],
            ['name' => 'Pyredol Syrup', 'unit' => 'bottle'],
            ['name' => 'Lavenola', 'unit' => 'pic'],
            ['name' => 'Waporal Inhalador', 'unit' => null],
            ['name' => 'Purafit Zinc', 'unit' => 'pic'],
            ['name' => 'Flutab', 'unit' => 'box-strip'],
            ['name' => 'Ciprocima 500', 'unit' => 'box-strip'],
            ['name' => 'Fotaz 100 Syrup', 'unit' => 'bottle'],
            ['name' => 'Amixime 100', 'unit' => 'bottle'],
            ['name' => 'CD Lxime 100 Syrup', 'unit' => 'bottle'],
            ['name' => 'Nystasyr', 'unit' => 'bottle'],
            ['name' => 'Fungistatin', 'unit' => 'bottle'],
            ['name' => 'Kamoks', 'unit' => 'bottle'],
            ['name' => 'Amiclav 457', 'unit' => 'bottle'],
            ['name' => 'Augram 228', 'unit' => 'bottle'],
            ['name' => 'Clavimox 228', 'unit' => 'bottle'],
            ['name' => 'Haemill Iron Tonic', 'unit' => 'bottle'],
            ['name' => 'CD Zithro', 'unit' => 'bottle'],
            ['name' => 'Unizithrin', 'unit' => 'bottle'],
            ['name' => 'Aziscot Syrup', 'unit' => 'bottle'],
            ['name' => 'CD Moxillin 250', 'unit' => 'bottle'],
            ['name' => 'Voxfer Drops', 'unit' => 'bottle'],
            ['name' => 'Tose Iron', 'unit' => 'bottle'],
            ['name' => 'Haematin Syrup', 'unit' => 'bottle'],
            ['name' => 'CNV Syrup', 'unit' => 'bottle'],
            ['name' => 'Halicare Syrup', 'unit' => 'bottle'],
            ['name' => 'Zinco Fate', 'unit' => null],
            ['name' => 'Zincsulphate Syrup', 'unit' => 'bottle'],
            ['name' => 'Ibuscot Susp', 'unit' => 'bottle'],
            ['name' => 'Bruflex 100 Sus', 'unit' => 'bottle'],
            ['name' => 'Paracetamol Barakat', 'unit' => 'bottle'],
            ['name' => 'Cetal 100/1ml', 'unit' => 'bottle'],
            ['name' => 'Nodigyl 200', 'unit' => 'bottle'],
            ['name' => 'Minicuf', 'unit' => 'bottle'],
            ['name' => 'Mini Guava', 'unit' => 'drop'],
            ['name' => 'Hilex', 'unit' => 'bottle'],
            ['name' => 'Allerban', 'unit' => 'bottle'],
            ['name' => 'Xelon 15mg/5ml', 'unit' => 'bottle'],
            ['name' => 'Isilin Syrup', 'unit' => 'bottle'],
            ['name' => 'Amihistin Syrup', 'unit' => 'bottle'],
            ['name' => 'Pharmacort', 'unit' => 'bottle'],
            ['name' => 'Scottus Syrup', 'unit' => 'bottle'],
            ['name' => 'Salbescot Syrup', 'unit' => 'bottle'],
            ['name' => 'Poly Vit', 'unit' => 'bottle'],
            ['name' => 'Vitcee Syrup', 'unit' => 'bottle'],
            ['name' => 'Ciprofloxocin Infusion', 'unit' => 'drip'],
            ['name' => 'Proscof Syrup', 'unit' => 'bottle'],
            ['name' => 'DO', 'unit' => 'pic'],
            ['name' => 'KD Max', 'unit' => 'pic'],
            ['name' => 'Vit C Lotion', 'unit' => 'pic'],
            ['name' => 'Vaseline Lotion', 'unit' => 'pic'],
            ['name' => 'Nilodol 500', 'unit' => 'pic'],
            ['name' => 'Heshma', 'unit' => 'pic'],
            ['name' => 'LG Alnaba', 'unit' => 'pic'],
            ['name' => 'Vigor Doctor Kids', 'unit' => 'tub'],
            ['name' => 'Digital Thermometer', 'unit' => 'pic'],
            ['name' => 'I Care', 'unit' => 'pic'],
            ['name' => 'Johnson Shampo Baby', 'unit' => 'pic'],
            ['name' => 'Baby Oil', 'unit' => 'pic'],
            ['name' => 'Fly Killing Bait', 'unit' => 'pic'],
            ['name' => 'Nopain Injee', 'unit' => 'box-amp'],
            ['name' => 'Baby Park 300ml', 'unit' => 'bottle'],
            ['name' => 'Sosi 280ml', 'unit' => null],
            ['name' => 'Lisodim 75/3ml', 'unit' => 'box-amp'],
            ['name' => 'Neomet 8mg/4ml', 'unit' => 'box-strip'],
            ['name' => 'Amixilin Syurp 250mg', 'unit' => 'bottle'],
            ['name' => 'Amixilin Syurp 125mg', 'unit' => 'bottle'],
            ['name' => 'Baby Pacifier S', 'unit' => 'pic'],
            ['name' => 'Surgical Gloves', 'unit' => 'pic'],
            ['name' => 'Disposable Insulin', 'unit' => 'pic'],
            ['name' => 'Cansinbant', 'unit' => 'pic'],
            ['name' => 'Amither L 20/120', 'unit' => 'box-strip'],
            ['name' => 'TG-11 Plus', 'unit' => 'pic'],
            ['name' => 'Amigel Suspension', 'unit' => 'pic'],
            ['name' => 'Re-lax', 'unit' => 'pic'],
            ['name' => 'Cotton', 'unit' => 'pic'],
            ['name' => 'Canulla 22', 'unit' => 'box'],
            ['name' => 'Canulla 24', 'unit' => 'box'],
            ['name' => 'Kondi Dent', 'unit' => 'pic'],
            ['name' => 'ZaHL', 'unit' => 'pic'],
            ['name' => 'Gauze Bandge', 'unit' => 'pic'],
            ['name' => 'Elastic Crepe Bandage', 'unit' => 'pic'],
            ['name' => 'Dandl', 'unit' => 'pic'],
            ['name' => 'Ultra Care', 'unit' => 'pic'],
            ['name' => 'Sutra', 'unit' => 'pic'],
            ['name' => 'Strawberry', 'unit' => 'pic'],
            ['name' => 'Vilget M50/1000', 'unit' => 'pic'],
            ['name' => 'Pedivit', 'unit' => 'box-strip'],
            ['name' => 'Waterfor Inj 5ml', 'unit' => 'amp'],
            ['name' => 'Waterfor Inj 10ml', 'unit' => 'amp'],
            ['name' => 'نظافات اذن', 'unit' => 'pic'],
            ['name' => 'اعواد اسنان', 'unit' => 'pic'],
            ['name' => 'Bitaplex Forte', 'unit' => 'box-strip'],
            ['name' => 'Atorvastatin 10mg', 'unit' => 'box'],
            ['name' => 'Coli-Urinal', 'unit' => 'bottle'],
            ['name' => 'Row-Chol', 'unit' => 'box'],
            ['name' => 'Rowatnex', 'unit' => 'box'],
            ['name' => 'Proximol', 'unit' => 'box'],
            ['name' => 'PotCit', 'unit' => 'pic'],
            ['name' => 'Zincot Plast', 'unit' => 'pic'],
            ['name' => 'Clivex', 'unit' => 'pic'],
            ['name' => 'Paraffin Gauze', 'unit' => 'pic'],
            ['name' => 'Cure-Aid', 'unit' => 'pic'],
            ['name' => 'Chromic Catgut', 'unit' => 'box'],
            ['name' => 'Surgical Sutures', 'unit' => 'pic'],
            ['name' => 'Lidocaine Inj', 'unit' => 'bottle'],
            ['name' => 'Catoskin Lotion', 'unit' => 'bottle'],
            ['name' => 'Sprit', 'unit' => 'pic'],
            ['name' => 'Potassium Permanganate', 'unit' => 'bottle'],
            ['name' => 'Povidine', 'unit' => 'box'],
            ['name' => 'Vita Vidone 10%', 'unit' => 'bottle'],
            ['name' => 'Vitcomis 1g', 'unit' => 'vial'],
            ['name' => 'Polymol 500mg', 'unit' => 'strip'],
            ['name' => 'Azadol Extra', 'unit' => 'box-strip'],
            ['name' => 'Marwastine 4ms', 'unit' => 'box-strip'],
            ['name' => 'Mask Face', 'unit' => 'pic'],
            ['name' => 'Male External Cathter', 'unit' => 'pic'],
            ['name' => 'Amifenac 25mg', 'unit' => 'strip'],
            ['name' => 'Amixillin 250', 'unit' => 'strip'],
            ['name' => 'Amibutamol 4mg', 'unit' => 'strip'],
            ['name' => 'Doxyscot 100mg', 'unit' => 'box'],
            ['name' => 'Syringe 10ml', 'unit' => 'pic'],
            ['name' => 'Amilox 500mg', 'unit' => 'strip'],
            ['name' => 'Ampilon-C 500', 'unit' => 'strip'],
            ['name' => 'Amidoxine 100mg', 'unit' => 'strip'],
            ['name' => 'Sanotact', 'unit' => 'box-tab'],
            ['name' => 'Dettol Soap', 'unit' => 'pic'],
            ['name' => 'Robb', 'unit' => 'pic'],
            ['name' => 'Alatrol 10mg', 'unit' => 'box-strip'],
            ['name' => 'Canulla S-26', 'unit' => 'box-pic'],
            ['name' => 'Canulla S-20', 'unit' => 'box-pic'],
            ['name' => 'Canulla S-18', 'unit' => 'pic'],
            ['name' => 'Cetmol Suspen', 'unit' => 'bottle'],
            ['name' => 'Keflen 250 Suspen', 'unit' => 'box'],
            ['name' => 'Aironyl Syrup', 'unit' => 'bottle'],
            ['name' => 'Hyomax Inje', 'unit' => 'amp'],
            ['name' => 'Sodium Bicarbonate', 'unit' => 'box'],
            ['name' => 'Samfagyl 250', 'unit' => 'strip'],
            ['name' => 'Ondanesteronmis', 'unit' => 'amp'],
            ['name' => 'Neo-drol Inj', 'unit' => 'vial'],
            ['name' => 'Amikacin 500/2ml', 'unit' => 'vial'],
            ['name' => 'Hemazon Inj', 'unit' => 'box-amp'],
            ['name' => 'Triamcort Inj', 'unit' => 'box'],
            ['name' => 'Genxat Inj', 'unit' => 'amp'],
            ['name' => 'Metadaxan Inj', 'unit' => 'box'],
            ['name' => 'Allermine Inj', 'unit' => 'amp'],
            ['name' => 'Buscovent-10', 'unit' => 'box-strip'],
            ['name' => 'CD Uremide', 'unit' => 'box'],
            ['name' => 'Lazjet 40mg', 'unit' => 'strip'],
            ['name' => 'Amiget Tab', 'unit' => 'strip'],
            ['name' => 'Panol 1000 drip', 'unit' => 'drip'],
            ['name' => 'Aziscot 250', 'unit' => 'box'],
            ['name' => 'DNS Drip', 'unit' => 'drip'],
            ['name' => 'Ringer Drip', 'unit' => 'drip'],
            ['name' => 'N.S Drip', 'unit' => 'drip'],
            ['name' => 'Glucose 5%', 'unit' => 'drip'],
            ['name' => 'Glucose 10%', 'unit' => 'drip'],
            ['name' => 'Fenugreek 300mg', 'unit' => 'box'],
            ['name' => 'Bioeast', 'unit' => 'box'],
            ['name' => 'Novitizer', 'unit' => 'pic'],
            ['name' => 'Mixtard 30', 'unit' => 'pic'],
            ['name' => 'Gacet-125 Suppositorise', 'unit' => 'box-supp'],
            ['name' => 'Gacet-250 Suppositorise', 'unit' => 'box-supp'],
            ['name' => 'Diclogesic Suppositorise', 'unit' => 'box'],
            ['name' => 'Glysup Suppositorise', 'unit' => 'box'],
            ['name' => 'Ronkotol Inhalation', 'unit' => 'box-amp'],
            ['name' => 'Caviar', 'unit' => 'box-pic'],
            ['name' => 'Rovista 20mg', 'unit' => 'box'],
            ['name' => 'Bisol 2.5mg', 'unit' => 'box'],
            ['name' => 'Candestan 16mg', 'unit' => 'box-strip'],
            ['name' => 'Diabend', 'unit' => 'box'],
            ['name' => 'Amiprazole 20', 'unit' => 'box'],
            ['name' => 'Trilodin', 'unit' => 'box-strip'],
            ['name' => 'Avenzor Fursemide', 'unit' => 'box'],
            ['name' => 'Allied Salbutomol', 'unit' => 'box'],
            ['name' => 'Tobramax D', 'unit' => 'drop'],
            ['name' => 'Clavenen 228mg', 'unit' => 'bottle'],
            ['name' => 'Fluocinolone', 'unit' => 'pic'],
            ['name' => 'Zecuf Rub', 'unit' => 'pic'],
            ['name' => 'Amitrim 240mg', 'unit' => 'bottle'],
            ['name' => 'Amibutamol Syrup', 'unit' => 'bottle'],
            ['name' => 'Kenazolo Shampo', 'unit' => 'box'],
            ['name' => 'Exizime Forte Oral', 'unit' => 'bottle'],
            ['name' => 'CD Methasalic Lotion', 'unit' => 'pic'],
            ['name' => 'Cento Soap', 'unit' => 'pic'],
            ['name' => 'IV Set', 'unit' => 'set'],
            ['name' => 'Calamine Lotion', 'unit' => 'bottle'],
            ['name' => 'HCA', 'unit' => 'pic'],
            ['name' => 'Right Sign HCG', 'unit' => 'box'],
            ['name' => 'Amiprofen 400', 'unit' => 'strip'],
            ['name' => 'Autest', 'unit' => 'pic'],
            ['name' => 'Prolol 40mg', 'unit' => 'box-strip'],
            ['name' => 'Prolol 10mg', 'unit' => 'box-strip'],
            ['name' => 'Potomax Citrate', 'unit' => 'pic'],
            ['name' => 'سيرلاك القمح والتمر', 'unit' => 'pic'],
            ['name' => 'سيرلاك القمح والفراولة', 'unit' => 'pic'],
            ['name' => 'ضفارة كبيرة', 'unit' => 'pic'],
            ['name' => 'صفارة صغيرة', 'unit' => 'pic'],
            ['name' => 'CD Dibrax', 'unit' => 'box-strip'],
            ['name' => 'Gentasaph Inj', 'unit' => 'box-amp'],
            ['name' => 'Benzathine 2.4', 'unit' => 'vial'],
            ['name' => 'Naglovic 750mg', 'unit' => 'box'],
            ['name' => 'Fusiturli B', 'unit' => 'tub'],
            ['name' => 'ناموسية اطفال', 'unit' => 'pic'],
            ['name' => 'ناموسية ديل', 'unit' => 'pic'],
            ['name' => 'ناموسية فردة', 'unit' => 'pic'],
            ['name' => 'Duphaston 10mg', 'unit' => 'box-strip'],
            ['name' => 'Heli Cure', 'unit' => 'box-strip'],
            ['name' => 'Milga', 'unit' => 'box-strip'],
            ['name' => 'Thyroxine Sodium 50', 'unit' => 'box'],
            ['name' => 'Lipanthy Supra', 'unit' => 'box'],
            ['name' => 'Eucarbon', 'unit' => 'box-strip'],
            ['name' => 'Adramark Inj', 'unit' => 'amp'],
            ['name' => 'Primaquine 15mg', 'unit' => 'strip'],
            ['name' => 'Tegretol 200mg', 'unit' => 'strip'],
            ['name' => 'Amaryl 1mg', 'unit' => 'box-strip'],
            ['name' => 'Dermovate', 'unit' => 'tub'],
            ['name' => 'Fertogard 50', 'unit' => 'box-strip'],
            ['name' => 'Kapron 500 Inj', 'unit' => 'box-amp'],
            ['name' => 'Amaryl 4mg', 'unit' => 'box-strip'],
            ['name' => 'Cold A Go', 'unit' => 'strip-tab'],
            ['name' => 'Inderal 10', 'unit' => 'box'],
            ['name' => 'Diamicron 60mr', 'unit' => 'strip'],
            ['name' => 'Nolvaelex 10', 'unit' => null],
            ['name' => 'Debocaine HCI', 'unit' => 'bottle'],
            ['name' => 'Cinnarizine 75', 'unit' => 'strip'],
            ['name' => 'Hydroxyurea 500', 'unit' => 'strip'],
            ['name' => 'Lamotrine 100', 'unit' => 'box-strip'],
            ['name' => 'Lamotrine 50', 'unit' => 'box-strip'],
            ['name' => 'Dexa Tablet', 'unit' => 'strip'],
            ['name' => 'Vitacide C', 'unit' => 'bottle'],
            ['name' => 'Diazi 5mg Inj', 'unit' => 'ampul'],
            ['name' => 'Valgestril', 'unit' => 'box'],
            ['name' => 'Oxyprogest', 'unit' => 'bottle'],
            ['name' => 'Inderal 40mg', 'unit' => 'box-strip'],
            ['name' => 'Urinex 36', 'unit' => 'box-strip'],
            ['name' => 'Dahab', 'unit' => 'box-tab'],
            ['name' => 'Lasix 20mg/2ml', 'unit' => 'box'],
            ['name' => 'Mepafuran 100', 'unit' => 'box-strip'],
            ['name' => 'AAzithro 500', 'unit' => 'box'],
            ['name' => 'Serpass 100mg', 'unit' => 'box'],
            ['name' => 'Serpass 500mg', 'unit' => 'box'],
            ['name' => 'C Retard 500', 'unit' => 'tab'],
            ['name' => 'Urinex 24', 'unit' => 'box'],
            ['name' => 'Pitem 800', 'unit' => 'strip'],
            ['name' => 'Pain Rest', 'unit' => 'strip'],
            ['name' => 'Praziquantel 600', 'unit' => 'box-tab'],
            ['name' => 'Paindex', 'unit' => 'box-strip'],
            ['name' => 'Rsunate 120', 'unit' => 'vial'],
            ['name' => 'Ramsun 60 Inj', 'unit' => 'vial'],
            ['name' => 'Falcivac 120 Inj', 'unit' => 'vial'],
            ['name' => 'Artedice', 'unit' => null],
            ['name' => 'Ramsun 180 Inj', 'unit' => 'vial'],
            ['name' => 'Artedice 30', 'unit' => 'vial'],
            ['name' => 'Pantolife 40 Inj', 'unit' => 'vial'],
            ['name' => 'Amri K', 'unit' => 'box-amp'],
            ['name' => 'Lactodel', 'unit' => 'box-strip'],
            ['name' => 'Capotril 50', 'unit' => 'box-strip'],
            ['name' => 'Biomycine Ointm', 'unit' => 'tub'],
            ['name' => 'Mini Guava N', 'unit' => 'drop'],
            ['name' => 'FPI Steadyfatal', 'unit' => 'box-strip'],
            ['name' => 'Silden 50mg', 'unit' => 'box'],
            ['name' => 'Tinika 500', 'unit' => 'strip'],
            ['name' => 'Phen Eptocan', 'unit' => 'amp'],
            ['name' => 'Ateno 100mg', 'unit' => 'box'],
            ['name' => 'Paludose P', 'unit' => 'tab'],
            ['name' => 'Baclofen Lobac', 'unit' => 'strip'],
            ['name' => 'Dapagliflozin 10', 'unit' => 'box'],
            ['name' => 'Verserc 16mg', 'unit' => 'box'],
            ['name' => 'Phenbital', 'unit' => 'strip'],
            ['name' => 'Gyna Mikozal', 'unit' => 'box'],
            ['name' => 'Pantulk Four M', 'unit' => 'pic'],
            ['name' => 'Wellman', 'unit' => 'box-strip'],
            ['name' => 'Hydrocortisone Inj', 'unit' => 'vial'],
            ['name' => 'Top Tulle', 'unit' => 'pic'],
            ['name' => 'Nasal Oxygen Cannullia', 'unit' => 'pic'],
            ['name' => 'Oxygen Mask Pediatric', 'unit' => 'pic'],
            ['name' => 'Nebulizer Mask Adult', 'unit' => 'pic'],
            ['name' => 'Nasal Canullia', 'unit' => 'pic'],
            ['name' => 'Oxygen Mask Adult', 'unit' => 'pic'],
            ['name' => 'Fortymox 0.5%', 'unit' => 'drop'],
            ['name' => 'Hyfresh Drop', 'unit' => 'drop'],
            ['name' => 'Brimonine Drop', 'unit' => 'drop'],
            ['name' => 'Tears Guard Drop', 'unit' => 'drop'],
            ['name' => 'DuoTrav Drop', 'unit' => 'drop'],
            ['name' => 'Plegica Drop', 'unit' => 'drop'],
            ['name' => 'Olohistine Drop', 'unit' => 'drop'],
            ['name' => 'Polyfresh Drop', 'unit' => 'drop'],
            ['name' => 'Epitaxol Drop', 'unit' => 'drop'],
            ['name' => 'Dexatrol Drop', 'unit' => 'drop'],
            ['name' => 'Xolamol Drop', 'unit' => 'drop'],
            ['name' => 'Conjy Chear 0.1%', 'unit' => 'drop'],
            ['name' => 'Fluca Drop', 'unit' => 'drop'],
        ];
    }
}
